### ISSUE TITLE
Telekom Link unklar

### ISSUE THREAD

**Issue by saschaludwig** [joanna159/covid19#3]
Unter https://github.com/joanna159/covid19#mobilfunkanbieter
Sagt der Link https://www.t-mobile.com/news/t-mobile-update-on-covid-19-response

"We are continuing to work with customers on a case-by-case basis to manage account issues. We do not have an offer available for 60 days of free service and encourage consumers to be cautious of social media posts that may include fraudulent numbers."

Angeblich gibt es "unlimited data plan" für alle bestehenden Telekom Kunden mit data plan. Aber das kann ich bisher noch nicht bestätigen. Es sieht so aus als wäre mein Volumen aktuell noch begrenzt.

**Comment by saschaludwig** [comment]
Und vermutlich betrifft es nur die USA:
https://www.t-mobile.com/brand/ceo-update-covid-19

Siehe Sigantur "CEO, T-Mobile USA"

**Comment by joanna159** [comment]
Danke, kläre ich.

**Comment by joanna159** [comment]
Die Telekom Deutschland hat ein eigenes Angebot rausgegeben.
Ich habe es angepasst.
https://twitter.com/deutschetelekom/status/1240548009148059648
